apiVersion: v1
kind: ServiceAccount
metadata:
  name: maas-api
  labels:
    {{- include "maas-api.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
