apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: gateway-rate-limits
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: maas-default-gateway
  limits:
    free:
      rates:
        - limit: 5
          window: 2m
      when:
        - predicate: |
            auth.identity.tier == "free"
      counters:
        - expression: auth.identity.userid
    premium:
      rates:
        - limit: 20
          window: 2m
      when:
        - predicate: |
            auth.identity.tier == "premium"
      counters:
        - expression: auth.identity.userid
    enterprise:
      rates:
        - limit: 50
          window: 2m
      when:
        - predicate: |
            auth.identity.tier == "enterprise"
      counters:
        - expression: auth.identity.userid