commonLabels:
  app.kubernetes.io/part-of: model-as-a-service
  app.kubernetes.io/component: api
  app.kubernetes.io/name: maas-api

maas:
  clusterDomain: apps.cluster-7d86.7d86.sandbox246.opentlc.com

redhatConnectivityLink:
  operator:
    channel: stable
    installPlanApproval: Automatic
    startingCSV: rhcl-operator.v1.2.0
