---
apiVersion: v1
kind: Secret
metadata:
  name: api-key-{{ .Values.maasUser.username }}
  namespace: maas-api-keys
  labels:
    authorino.kuadrant.io/managed-by: authorino
  annotations:
    user.authorino.kuadrant.io/userid: "maas-user"
    user.authorino.kuadrant.io/groups: "tier-free-users"
stringData:
  api_key: "{{ .Values.maasUser.apiKey }}"
